import type { Metadata } from "next";
import "@/styles/globals.css";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../assets/fonts/pretendard/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.variable} flex min-h-screen flex-col items-center`}
      >
        {children}
      </body>
    </html>
  );
}
